W5D2/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs
  resources :posts do
    resources :comments, only: [:show]
  end
  resources :comments, only: [:create, :destroy]
  post '/posts/:id/upvote', to: 'posts#upvote'
  post '/posts/:id/downvote', to: 'posts#downvote'
  post '/posts/:id/resetvote', to: 'posts#resetvote'
  post '/comments/:id/upvote', to: 'comments#upvote'
  post '/comments/:id/downvote', to: 'comments#downvote'
  post '/comments/:id/resetvote', to: 'comments#resetvote'

end

W5D2/reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable

  validates :content, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

end

W5D2/reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    post = Post.find(params[:comment][:post_id])
    @comment.post = post
    @comment.parent_comment_id = params[:comment][:parent_comment_id]
    if @comment.save
      redirect_to post_url(post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.delete
    render posts_url(post)
  end

  def upvote
    vote(1)
  end

  def resetvote
    vote(0)
  end

  def downvote
    vote(-1)
  end

  def vote(val)
    @comment = Comment.find(params[:id])
    @vote = @comment.votes.find_or_initialize_by(liker: current_user)
    unless @vote.update(value: val)
      flash[:errors] = @vote.errors.full_messages
    end

    redirect_to post_comment_url(@comment)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

W5D2/reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

W5D2/reddit_clone/app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>
<h3>by: <%= @comment.author.username %></h3>
<%= button_to "i lik dis", "/comments/#{@comment.id}/upvote"%>
<%= button_to "screw dis", "/comments/#{@comment.id}/downvote"%>
<%= button_to "i feel neutral bout dis", "/comments/#{@comment.id}/resetvote"%>



dis many ppl lik dis: <%= @comment.num_votes %>


<ul>
  <% @comment.child_comments.each do |child| %>
  <%= render "shared/comment", comment: child, post: @comment.post %>
  <% end %>
</ul>

<form class="" action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <label>Comment:
    <textarea name="comment[content]"></textarea>
  </label>
  <input type="submit" name="" value="post dis comment!">

</form>

<%= button_to "delet dis comment", comment_url, method: :delete %>

<%= link_to "bak 2 original post pls", post_url(@comment.post.id) %>