W5D2/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs
  resources :posts do
    resources :comments, only: [:show]
  end
  resources :comments, only: [:create, :destroy]
  post '/posts/:id/upvote', to: 'posts#upvote'
  post '/posts/:id/downvote', to: 'posts#downvote'
  post '/posts/:id/resetvote', to: 'posts#resetvote'
  post '/comments/:id/upvote', to: 'comments#upvote'
  post '/comments/:id/downvote', to: 'comments#downvote'
  post '/comments/:id/resetvote', to: 'comments#resetvote'

end

W5D2/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  include Likeable


  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Comment


end

W5D2/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_author

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save!
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to subs_url
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def delete
    @post = Post.find(params[:id])
    @post.delete
    redirect_to subs_url
  end

  def upvote
    vote(1)
  end

  def resetvote
    vote(0)
  end

  def downvote
    vote(-1)
  end

  def vote(val)
    @post = Post.find(params[:id])
    @vote = @post.votes.find_or_initialize_by(liker: current_user)
    unless @vote.update(value: val)
      flash[:errors] = @vote.errors.full_messages
    end

    redirect_to post_url(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def check_author
    if ["edit"].include?(params[:action])
      post = Post.find(params[:id])
      unless current_user.posts.include?(post)
        flash[:errors] = "u cannot edit dis post bak off nao!"
        redirect_to post_url(post)
      end
    end
  end
end

W5D2/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/reddit_clone/app/views/posts/edit.html.erb
<h1>we fixin dis post good</h1>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <input type="hidden" name="_method" value="patch">

  <label>Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>Url(optional):
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>Content:
     <textarea name="post[content]"><%= @post.content %></textarea>
  </label>

  <label>Subs</label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %> >
    </label>
  <% end %>

  <input type="submit" name="" value="submit plz">
</form>

W5D2/reddit_clone/app/views/posts/new.html.erb
<h1>makin a nuw post</h1>

<form class="" action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title:
    <input type="text" name="post[title]" value="">
  </label>
  <label>Url(optional):
    <input type="text" name="post[url]" value="">
  </label>
  <br>
  <label>Content:
     <textarea name="post[content]"></textarea>
  </label>
  <br>

  <label>Subs:</label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %> >
    </label>
  <% end %>
  <br>

  <input type="submit" name="" value="submit plz">
</form>

W5D2/reddit_clone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% unless @post.url.empty? %>
  url: <%= @post.url %>
<% end %>


<% if @post.content %>
  <p>content: <%= @post.content %></p>
<% end %>
dis many ppl lik dis: <%= @post.num_votes %>
<%= button_to "i lik dis", "/posts/#{@post.id}/upvote"%>
<%= button_to "screw dis", "/posts/#{@post.id}/downvote"%>
<%= button_to "i feel neutral bout dis", "/posts/#{@post.id}/resetvote"%>

<label>Comments:
  <ul>
    <% @post.comments.includes(:author).each do |comment| %>
      <% if comment.parent_comment_id.nil? %>
        <li> <%= render "/shared/comment.html.erb", comment: comment, post: @post %> </li>
      <% end %>
    <% end %>
  </ul>
</label>


<form class="" action="<%=comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <label>Comment:
    <textarea name="comment[content]"></textarea>
  </label>
  <input type="submit" name="" value="post dis comment!">
</form>



<h2>Subs:</h2>
<ul>
  <% @post.subs.each do |sub| %>
  <li><%= link_to "#{sub.title}", sub_url(sub) %></li>
  <% end %>
</ul>


<br>
<%= link_to "edit dis post", edit_post_url(@post)%>